### ISSUE TITLE
Unable to resolve action `benelan/milestone-action@v2`, unable to find version `v2`

### ISSUE THREAD

**Issue by andrewjswan** [benelan/milestone-action#251]
### Actual Behavior

Getting action download info
Error: Unable to resolve action `benelan/milestone-action@v2`, unable to find version `v2`

### Expected Behavior

-

### Reproduction Steps

```
name: "Workflow / Milestone"

on:
  pull_request:
    types: [closed]

jobs:
  add:
    runs-on: ubuntu-latest
    steps:
      - uses: benelan/milestone-action@v2
```

### Reproduction Version

v2.0.0
